version: '3'
services:
  exodus-mysql-dev:
    image: mysql:8.0.16
    container_name: exodus-mysql-dev
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=exodus
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/mysql-db:/docker-entrypoint-initdb.d
      - ./mysql/storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined