version: '3'
services:
  exodus-mysql:
    image: mysql:8.0.16
    container_name: exodus-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=exodus
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/mysql-db:/docker-entrypoint-initdb.d
      - ./mysql/storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
  exodus-frontend:
    container_name: exodus-frontend
    image: exodus-frontend
    ports:
      - 3000:3000
  exodus-backend:
    container_name: exodus-backend
    image: exodus-backend
    ports:
      - 3333:3333
    depends_on:
      - exodus-mysql